#!/usr/bin/env bash

cd `dirname "$0"`
DEST=../src/main/res/drawable/
DEST_LIST=../src/main/java/generated/images.kt
MAXSIZE=312x312

mkdir -p "$DEST"
mkdir -p `dirname "$DEST_LIST"`

echo "// generated by :/images/convert-all.sh - DO NOT EDIT" > "$DEST_LIST"
echo "package generated" >> "$DEST_LIST"
echo >> "$DEST_LIST"
echo "import dev.bojidar_bg.memory.R" >> "$DEST_LIST"
echo "val images = listOf(" >> "$DEST_LIST"

for image in ./*.svg; do
    destimage=`basename "$image" | tr '[:upper:]' '[:lower:]' | tr -dC '[a-z0-9]'`
    magick -size "$MAXSIZE" -background none rsvg:"$image" "$DEST"/"$destimage".png
    if ! [[ "$destimage" =~ "icon" ]]; then
        echo "  R.drawable.$destimage," >> "$DEST_LIST"
    fi
done

echo ")" >> "$DEST_LIST"
